version: '2'
services:
  sharedbox:
    image: busybox
    volumes:
      - /var/log
      - /var/run
  proxy:
    build:
      context: ./nginx
      dockerfile: Dockerfile # we mean the ./nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - ./logs:/var/log
    volumes_from:
      - sharedbox
  db:
    image: mdillon/postgis:9.6
    ports:
      - 5432:5432
    environment: &app_server_enviroment_vars
      - POSTGRES_USER=${RAOW_DB_USER}
      - POSTGRES_PASSWORD=${RAOW_DB_PASS}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  app:
    build:
      context: ./app
      dockerfile: Dockerfile # we mean the ./app/Dockerfile
    volumes:
      - ./logs:/app/log
    volumes_from:
      - sharedbox
    environment:
      RAILS_ENV: production
      RAOW_DB_USER: ${RAOW_DB_USER}
      RAOW_DB_PASS: ${RAOW_DB_PASS}
      DB_HOST: db
      MAX_THREADS: 2     # Puma threads,  watch out so you don't run out of DB connection pool
      WEB_CONCURRENCY: 1 # should match CPU of server
      SECRET_KEY_BASE: 19d07059ab81ff584bd8fd7be03ed765c63f5f4c3518d05f39b41c7152134e294b2f09cbf5d925045caab0ef6475862fc42c8e6b35d63e353a1472057e90f8c4
volumes:
  data:
    external: false
